function complete = checkConfPreDissection(energy_level)
    complete = false;

    % Check the objective and move it into the light path
    r1 = questdlg(...
        {'1) Verify UV objective is clean with secondary camera,',...
         '2) Switch UV objective into light path',...
         '3) Clear External Interlock error'}, ...
         'P.U.M.P. Dissection','Complete','Abort','Abort');

    if ~strcmp(r1,'Complete')
       warndlg('Dissection Aborted.','P.U.M.P. Dissection');
       return
    end

    % Set software parameters
    r2 = questdlg(...
        {'In ATLEX Laser Control Software: ',...
         '   Set MODE to Energy stab.',...
         '   Set STANDBY to ON',...
         '   Set TIRGGER to External Trigger',...
         '   Set TRIGGER to RUN',...
        ['   Set Energy[mJ] to ' num2str(energy_level) ''],...
         '  '}, ...
         'P.U.M.P. Dissection','Complete','Abort','Abort');

    if ~strcmp(r2,'Complete')
       warndlg('Dissection Aborted.','P.U.M.P. Dissection');
       return
    end

    complete = true;
    
end